# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems:
    - jekyll-paginate
paginate_path: "page:num"
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://rafaelvzago.github.io/
baseurl:
title: Rafael Zago
author: Rafael Zago
description: $random snippets
avatar: eu.jpg
logo: logo.png
email: contato@rafaelzago.eti.br
github: rafaelvzago # username
twitter: rafaelvzago
linkedin: rafaelvzago
stackoverflow: rafaelvzago
#Comment out if you don't want disqus
disqus: rafaelvzago
google_analytics: UA-56644904-1


# needed for travis-ci build
exclude: [vendor]
